version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://myusername:mypassword@db:5432/countries_populations_service

  db:
    image: postgres
    environment:
      POSTGRES_USER: myusername
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: countries_populations_service
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
